### ISSUE TITLE
PHP Notice:  Undefined index: name in Black/Validator.php on line 27

### ISSUE THREAD

**Issue by andrenventer** [fixwa/BlackFramework#9]
Fresh install.

DB connection is correct and DB installed.
Sign up: produces this error

POST

Array
(
    [signature] => Array
        (
            [uniqueId] => 000000005fb0847b000000012ef11dba
            [csrfHash] => 390a693687e828976d330bf2b73f7c4e450004b8
        )

```
[name] => admin
[email] => user@gmail.com
[password] => password
```

)

[Sun Oct 18 10:26:17 2015] PHP Stack trace:
[Sun Oct 18 10:26:17 2015] PHP   1. {main}() /Users/nomad/Projects/BlackFramework-master/index.php:0
[Sun Oct 18 10:26:17 2015] PHP   2. Black\Application->init() /Users/nomad/Projects/BlackFramework-master/index.php:12
[Sun Oct 18 10:26:17 2015] PHP   3. Black\Application->dispatch() /Users/nomad/Projects/BlackFramework-master/Black/Application.php:10
[Sun Oct 18 10:26:17 2015] PHP   4. Black\Container::get() /Users/nomad/Projects/BlackFramework-master/Black/Application.php:16
[Sun Oct 18 10:26:17 2015] PHP   5. Black\Dispatcher->Black{closure}() /Users/nomad/Projects/BlackFramework-master/Black/Container.php:45
[Sun Oct 18 10:26:17 2015] PHP   6. Application\Modules\User\Controllers\RegistrationController->registrationAction() /Users/nomad/Projects/BlackFramework-master/Black/Dispatcher.php:61
[Sun Oct 18 10:26:17 2015] PHP   7. Black\Models\EntityModel->saveFromArray() /Users/nomad/Projects/BlackFramework-master/Application/Modules/User/Controllers/RegistrationController.php:21
[Sun Oct 18 10:26:17 2015] PHP   8. Black\Models\EntityModel->validate() /Users/nomad/Projects/BlackFramework-master/Black/Models/EntityModel.php:21
[Sun Oct 18 10:26:17 2015] PHP   9. Black\Validator->passes() /Users/nomad/Projects/BlackFramework-master/Black/Models/EntityModel.php:50

**Comment by fixwa** [comment]
The database needs to be populated first. I just pushed a new README file with better instructions. 
Thanks for checking.

Fixed by: https://github.com/fixwa/BlackFramework/commit/78fe70d26d4f8e0ae6e1e5c9983e6e0b2ae5f919
